module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: null
version: 1
ghc-args: []
excluded-modules:
- src/A.hs
- src/B.hs
- src/Json.hs
- src/Main.hs
- src/Physics.hs
- src/Simulation.hs
- src/Test/Main.hs
- src/World.hs
